repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: flake8
        exclude: (mysite/portfolio/tests|mysite/portfolio/migrations)
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        exclude: (mysite/portfolio/tests|mysite/portfolio/migrations)
